export const ListValuta = [
{kode: "ADP", nama: "Andorran Peseta"},
{kode: "AED", nama: "UAE Dirham"},
{kode: "AFA", nama: "Afghani"},
{kode: "AFN", nama: "Afghani"},
{kode: "ALL", nama: "Lek"},
{kode: "AMD", nama: "Armenian Dram"},
{kode: "ANG", nama: "Netherlands Antillian Guilder"},
{kode: "AOA", nama: "Kwanza"},
{kode: "AON", nama: "New Kwanza"},
{kode: "ARS", nama: "Argentina Peso"},
{kode: "ATS", nama: "Schilling"},
{kode: "AUD", nama: "Australian Dollar"},
{kode: "AWG", nama: "Aruban Guilder"},
{kode: "AZM", nama: "Azerbaijanian Manat"},
{kode: "AZN", nama: "Azerbaijanian Manat"},
{kode: "BAM", nama: "Convertible Marks"},
{kode: "BBD", nama: "Barbados Dollar"},
{kode: "BDT", nama: "Taka"},
{kode: "BEF", nama: "Belgian Franc"},
{kode: "BGL", nama: "Lev"},
{kode: "BGN", nama: "Bulgarian Lev"},
{kode: "BHD", nama: "Bahraini Dinar"},
{kode: "BIF", nama: "Burundi Franc"},
{kode: "BMD", nama: "Bermudian Dollar"},
{kode: "BND", nama: "Brunei Dollar"},
{kode: "BOB", nama: "Boliaano"},
{kode: "BOV", nama: "Mvdol"},
{kode: "BRL", nama: "Brazilian Real"},
{kode: "BSD", nama: "Bahamian Dollar"},
{kode: "BTN", nama: "Ngultrum"},
{kode: "BWP", nama: "Pula"},
{kode: "BYB", nama: "Belarussian Ruble"},
{kode: "BYR", nama: "Belarussian Ruble"},
{kode: "BZD", nama: "Belize Dollar"},
{kode: "CAD", nama: "Canadian Dollar"},
{kode: "CDF", nama: "Congolese Franc"},
{kode: "CHE", nama: "WIR Euro"},
{kode: "CHF", nama: "Swiss Franc"},
{kode: "CHW", nama: "WIR Franc"},
{kode: "CLF", nama: "Unidades de fomento"},
{kode: "CLP", nama: "Chilean Peso"},
{kode: "CNY", nama: "Yuan Renminbi"},
{kode: "COP", nama: "Colombian Peso"},
{kode: "COU", nama: "Unidad de Valor Real"},
{kode: "CRC", nama: "Costa Rican Colon"},
{kode: "CUC", nama: "Peso Convertible"},
{kode: "CUP", nama: "Cuban Peso"},
{kode: "CVE", nama: "Cape Verde Escudo"},
{kode: "CYP", nama: "Cyprus Pound"},
{kode: "CZK", nama: "Czech Koruna"},
{kode: "DEM", nama: "Deustche Mark"},
{kode: "DJF", nama: "Djibouti Franc"},
{kode: "DKK", nama: "Danish Krone"},
{kode: "DOP", nama: "Domincan Peso"},
{kode: "DZD", nama: "Algerian Dinar"},
{kode: "ECS", nama: "Sucre"},
{kode: "EEK", nama: "Kroon"},
{kode: "EGP", nama: "Egyptian Pound"},
{kode: "ERN", nama: "Nakfa"},
{kode: "ESP", nama: "Spainish peseta"},
{kode: "ETB", nama: "Ethiopian Birr"},
{kode: "FIM", nama: "Markka"},
{kode: "FJD", nama: "Fiji Dollar"},
{kode: "FKP", nama: "Falkland Islands Pound"},
{kode: "FRF", nama: "Franch Franc"},
{kode: "GBP", nama: "Pound Sterling"},
{kode: "GEK", nama: "Georgian Coupon"},
{kode: "GEL", nama: "Lari"},
{kode: "GHC", nama: "Cedi"},
{kode: "GHS", nama: "Cedi"},
{kode: "GIP", nama: "Gibraltar Pound"},
{kode: "GMD", nama: "Dalasi"},
{kode: "GNF", nama: "Guinea Franc"},
{kode: "GRD", nama: "Drachma"},
{kode: "GTQ", nama: "Quetzal"},
{kode: "GWP", nama: "Guinea-Bissau Peso"},
{kode: "GYD", nama: "Guyana Dollar"},
{kode: "HKD", nama: "Hong Kong Dollar"},
{kode: "HNL", nama: "Lempira"},
{kode: "HRD", nama: "Croatian Dinar"},
{kode: "HRK", nama: "Kuna"},
{kode: "HTG", nama: "Gourde"},
{kode: "HUF", nama: "Forint"},
{kode: "IDR", nama: "Rupiah"},
{kode: "IEP", nama: "Irish Pound"},
{kode: "ILS", nama: "Shekel"},
{kode: "INR", nama: "Indian Rupee"},
{kode: "IQD", nama: "Iraqi Dinar"},
{kode: "IRR", nama: "Iranian Rial"},
{kode: "ISK", nama: "Iceland Krona"},
{kode: "ITL", nama: "Italian Lira"},
{kode: "JMD", nama: "Jamaican Dollar"},
{kode: "JOD", nama: "Jordanian Dinar"},
{kode: "JPY", nama: "Yen"},
{kode: "KES", nama: "Kenyan Shilling"},
{kode: "KGS", nama: "Som"},
{kode: "KHR", nama: "Riel"},
{kode: "KMF", nama: "Comoro Franc"},
{kode: "KPW", nama: "North Korean Won"},
{kode: "KRW", nama: "Won"},
{kode: "KWD", nama: "Kuwauti Dinar"},
{kode: "KYD", nama: "Cayman Islands Dollar"},
{kode: "KZT", nama: "Tenge"},
{kode: "LAK", nama: "Kip"},
{kode: "LBP", nama: "Lebanese Pound"},
{kode: "LKR", nama: "Sri Langka Rupee"},
{kode: "LRD", nama: "Liberian Dollar"},
{kode: "LSL", nama: "Loli"},
{kode: "LTL", nama: "Lithuanian Litas"},
{kode: "LUF", nama: "Luxembourg Franc"},
{kode: "LVL", nama: "Latvian Lats#"},
{kode: "LVR", nama: "Latvian Ruble"},
{kode: "LYD", nama: "Libyan Dinar"},
{kode: "MAD", nama: "Moroccoan Dirham"},
{kode: "MDL", nama: "Moldovan Leu"},
{kode: "MGA", nama: "Malagasy Ariary"},
{kode: "MGF", nama: "Malagasy Franc"},
{kode: "MKD", nama: "Denar"},
{kode: "MMK", nama: "Kyat"},
{kode: "MNT", nama: "Tugrik"},
{kode: "MOP", nama: "Pataca"},
{kode: "MRO", nama: "Ouguiya"},
{kode: "MTL", nama: "Mallese Lira"},
{kode: "MUR", nama: "Mauritius Pupee"},
{kode: "MVR", nama: "Rufiyaa"},
{kode: "MWK", nama: "Kwacha"},
{kode: "MXN", nama: "Mexican Nuevo Peso"},
{kode: "MXV", nama: "Mexican Unidad de Inversion (UDI)"},
{kode: "MYR", nama: "Malaysian Ringgit"},
{kode: "MZM", nama: "Metical"},
{kode: "MZN", nama: "Metical"},
{kode: "NAD", nama: "Namibia Dollar"},
{kode: "NGN", nama: "Naira"},
{kode: "NIO", nama: "Cordoba Oro"},
{kode: "NLG", nama: "Netherlands Guilder"},
{kode: "NOK", nama: "Norwegian Krone"},
{kode: "NPR", nama: "Nepalese Rupee"},
{kode: "NZD", nama: "New Zealand Dollar"},
{kode: "OMR", nama: "Rial Omani"},
{kode: "PAB", nama: "Balboa/US Dollar"},
{kode: "PEN", nama: "Nuevo Sol"},
{kode: "PGK", nama: "Kina"},
{kode: "PHP", nama: "Philippines Peso"},
{kode: "PKR", nama: "Pakistan Rupee"},
{kode: "PLN", nama: "Zloty"},
{kode: "PLZ", nama: "Zloty"},
{kode: "PTE", nama: "Portuguese Escudo"},
{kode: "PYG", nama: "Guarani"},
{kode: "QAR", nama: "Qatari Rial"},
{kode: "ROL", nama: "Leu"},
{kode: "RON", nama: "New Leu"},
{kode: "RSD", nama: "Serbian Dinar"},
{kode: "RUB", nama: "Russian Ruble"},
{kode: "RUR", nama: "Russian Ruble"},
{kode: "RWF", nama: "Rwanda Franc"},
{kode: "SAR", nama: "Saudi Riyal"},
{kode: "SBD", nama: "Solomon Islands Dollar"},
{kode: "SCR", nama: "Seychelles Rupee"},
{kode: "SDD", nama: "Sudanese Dinar"},
{kode: "SDG", nama: "Sudanese Pound"},
{kode: "SDP", nama: "Sudanese Pound"},
{kode: "SEK", nama: "Swedish Krone"},
{kode: "SGD", nama: "Singapore Dollar"},
{kode: "SHP", nama: "St. Helena Pound"},
{kode: "SIT", nama: "Tolar"},
{kode: "SKK", nama: "Slovak Koruna"},
{kode: "SLL", nama: "Leone"},
{kode: "SOS", nama: "Somalia Shilling"},
{kode: "SRD", nama: "Surinam Dollar"},
{kode: "SRG", nama: "Surinam Guilder"},
{kode: "STD", nama: "Dobra"},
{kode: "SVC", nama: "El Salvador Colon"},
{kode: "SYP", nama: "Syrian Pound"},
{kode: "SZL", nama: "Lilangeni"},
{kode: "THB", nama: "Baht"},
{kode: "TJS", nama: "Somoni"},
{kode: "TMM", nama: "Manat"},
{kode: "TMT", nama: "Manat"},
{kode: "TND", nama: "Tunisian Dinar"},
{kode: "TOP", nama: "Pa'anga"},
{kode: "TRL", nama: "Turkish Lira"},
{kode: "TRY", nama: "Turkish Lira"},
{kode: "TTD", nama: "Trinidad and Tobago Dollar"},
{kode: "TWD", nama: "New Taiwan Dollar"},
{kode: "TZS", nama: "Tanzania Shilling"},
{kode: "UAH", nama: "Hryvnia"},
{kode: "UAK", nama: "Karbovanet"},
{kode: "UGX", nama: "Uganda Shilling"},
{kode: "USD", nama: "US Dollar"},
{kode: "UYI", nama: "Uruguay Peso en Unidades Indexadas"},
{kode: "UYU", nama: "Peso Uruguayo"},
{kode: "UZS", nama: "Ubekistan Sum"},
{kode: "VEB", nama: "Bolivar"},
{kode: "VEF", nama: "Bolivar Fuerte"},
{kode: "VND", nama: "Dong"},
{kode: "VUV", nama: "Vatu"},
{kode: "WST", nama:	"Tala"},
{kode: "YER", nama: "Yemeni Rial"},
{kode: "YUN", nama: "New Yugosslavian"},
{kode: "ZAL", nama: "Financial Rand"},
{kode: "ZAR", nama: "Rand"},
{kode: "ZMK", nama: "Kwacha"},
{kode: "ZWD", nama: "Zimbabwe Dollar"},
{kode: "ZWL", nama: "Zimbabwe Dollar"},
].map(item => ({ label: `${item.kode} - ${item.nama}`, value: item.kode }));