export const ListKategoriBarang = [
    {kodeDokumen: "23", kodeKategoriBarang: "01", uraian: "BARANG UNTUK DITIMBUN"},
    {kodeDokumen: "23", kodeKategoriBarang: "02", uraian: "BARANG UNTUK KEPERLUAN PENGUSAHAAN"},
    {kodeDokumen: "23", kodeKategoriBarang: "11", uraian: "UNTUK BAHAN BAKU/BAHAN PENOLONG"},
    {kodeDokumen: "23", kodeKategoriBarang: "12", uraian: "UNTUK PENGEMAS/ALAT BANTU PENGEMAS"},
    {kodeDokumen: "23", kodeKategoriBarang: "13", uraian: "UNTUK PERALATAN UNTUK PEMBANGUNAN, PERLUASAN, ATAU KONSTRUKSI KB"},
    {kodeDokumen: "23", kodeKategoriBarang: "14", uraian: "UNTUK BARANG MODAL DAN/ATAU SPAREPARTS BARANG MODAL"},
    {kodeDokumen: "23", kodeKategoriBarang: "15", uraian: "UNTUK BARANG CONTOH"},
    {kodeDokumen: "23", kodeKategoriBarang: "16", uraian: "UNTUK BARANG JADI GUNA DIGABUNG DENGAN HASIL PRODUKSI"},
    {kodeDokumen: "23", kodeKategoriBarang: "17", uraian: "UNTUK BARANG REIMPOR"},
    {kodeDokumen: "23", kodeKategoriBarang: "18", uraian: "UNTUK PERALATAN PERKANTORAN"},
    {kodeDokumen: "23", kodeKategoriBarang: "19", uraian: "BARANG UNTUK KEPERLUAN PENANGANAN COVID19"},
    {kodeDokumen: "23", kodeKategoriBarang: "21", uraian: "UNTUK BARANG YANG DITIMBUN DI GB"},
    {kodeDokumen: "23", kodeKategoriBarang: "22", uraian: "UNTUK BARANG REIMPOR"},
    {kodeDokumen: "23", kodeKategoriBarang: "31", uraian: "UNTUK BARANG UNTUK DIPAMERKAN"},
    {kodeDokumen: "23", kodeKategoriBarang: "32", uraian: "UNTUK BARANG UNTUK MENDUKUNG KEPERLUAN PAMERAN"},
    {kodeDokumen: "23", kodeKategoriBarang: "33", uraian: "UNTUK BARANG REIMPOR"},
    {kodeDokumen: "23", kodeKategoriBarang: "41", uraian: "UNTUK BARANG YANG DITIMBUN DI TBB"},
    {kodeDokumen: "23", kodeKategoriBarang: "42", uraian: "UNTUK BARANG REIMPOR"},
    {kodeDokumen: "23", kodeKategoriBarang: "51", uraian: "UNTUK BARANG LELANG"},
    {kodeDokumen: "23", kodeKategoriBarang: "52", uraian: "UNTUK SPAREPARTS"},
    {kodeDokumen: "23", kodeKategoriBarang: "53", uraian: "UNTUK BARANG REIMPOR"},
    {kodeDokumen: "23", kodeKategoriBarang: "61", uraian: "UNTUK BARANG YANG DITIMBUN DI KDUB"},
    {kodeDokumen: "23", kodeKategoriBarang: "62", uraian: "UNTUK BARANG REIMPOR"},
    {kodeDokumen: "25", kodeKategoriBarang: "1", uraian: "HASIL PRODUKSI"},
    {kodeDokumen: "25", kodeKategoriBarang: "2", uraian: "BAHAN BAKU"},
    {kodeDokumen: "25", kodeKategoriBarang: "3", uraian: "BARANG MODAL"},
    {kodeDokumen: "25", kodeKategoriBarang: "4", uraian: "PERALATAN KANTOR"},
    {kodeDokumen: "25", kodeKategoriBarang: "5", uraian: "SISA DARI PROSES PRODUKSI/LIMBAH (WASTE/SCRAP) DAN/ATAU SISA ATAU BEKAS PENGEMAS"},
    {kodeDokumen: "25", kodeKategoriBarang: "6", uraian: "BARANG YANG DITIMBUN UNTUK DIJUAL"},
    {kodeDokumen: "25", kodeKategoriBarang: "7", uraian: "BARANG YANG DIPAMERKAN UNTUK DIJUAL"},
    {kodeDokumen: "25", kodeKategoriBarang: "8", uraian: "BARANG LAINNYA"},
    {kodeDokumen: "25", kodeKategoriBarang: "9", uraian: "BARANG UNTUK KEPERLUAN PENANGANAN COVID19"},
    {kodeDokumen: "25", kodeKategoriBarang: "10", uraian: "BARANG CONTOH"},
];