export const ListJenisKemasan = [
    { value: "1A", label: "Drum, steel" },
    { value: "1B", label: "Drum, aluminium" },
    { value: "1D", label: "Drum, plywood" },
    { value: "1F", label: "Container, flexible" },
    { value: "1G", label: "Drum, fibre" },
    { value: "1W", label: "Drum, wooden" },
    { value: "2C", label: "Barrel, wooden" },
    { value: "3A", label: "Jerrican, steel" },
    { value: "3H", label: "Jerrican, plastic" },
    { value: "43", label: "Bag, super bulk" },
    { value: "44", label: "Bag, polybag" },
    { value: "4A", label: "Box, steel" },
    { value: "4B", label: "Box, aluminium" },
    { value: "4C", label: "Box, natural wood" },
    { value: "4D", label: "Box, plywood" },
    { value: "4F", label: "Box, reconstituted wood" },
    { value: "4G", label: "Box, fibreboard" },
    { value: "4H", label: "Box, plastic" },
    { value: "5H", label: "Bag, woven plastic" },
    { value: "5L", label: "Bag, textile" },
    { value: "5M", label: "Bag, paper" },
    { value: "6H", label: "Composite packaging, plastic receptacle" },
    { value: "6P", label: "Composite packaging, glass receptacle" },
    { value: "7A", label: "Case, car" },
    { value: "7B", label: "Case, wooden" },
    { value: "8A", label: "Pallet, wooden" },
    { value: "8B", label: "Crate, wooden" },
    { value: "8C", label: "Bundle, wooden" },
    { value: "AA", label: "Intermediate bulk container, rigid plastic" },
    { value: "AB", label: "Receptacle, fibre" },
    { value: "AC", label: "Receptacle, paper" },
    { value: "AD", label: "Receptacle, wooden" },
    { value: "AE", label: "Aerosol" },
    { value: "AF", label: "Pallet, modular, collars 80cms * 60cms" },
    { value: "AG", label: "Pallet, shrinkwrapped" },
    { value: "AH", label: "Pallet, 100cms * 110cms" },
    { value: "AI", label: "Clamshell" },
    { value: "AJ", label: "Cone" },
    { value: "AL", label: "Ball" },
    { value: "AM", label: "Ampoule, non protected" },
    { value: "AP", label: "Ampoule, protected" },
    { value: "AT", label: "Atomizer" },
    { value: "AV", label: "Capsule" },
    { value: "B4", label: "Belt" },
    { value: "BA", label: "Barrel" },
    { value: "BB", label: "Bobbin" },
    { value: "BC", label: "Bottlecrate, bottlerack" },
    { value: "BD", label: "Board" },
    { value: "BE", label: "Bundle" },
    { value: "BF", label: "Balloon, non-protected" },
    { value: "BG", label: "Bag" },
    { value: "BH", label: "Bunch" },
    { value: "BI", label: "Bin" },
    { value: "BJ", label: "Bucket" },
    { value: "BK", label: "Basket" },
    { value: "BL", label: "Bale, compressed" },
    { value: "BM", label: "Basin" },
    { value: "BN", label: "Bale, non -compressed" },
    { value: "BO", label: "Bottle, non-protected, cylindrical" },
    { value: "BP", label: "Balloon, protected" },
    { value: "BQ", label: "Bottle, protected cylindrical" },
    { value: "BR", label: "Bar" },
    { value: "BS", label: "Bottle, non-protected, bulbous" },
    { value: "BT", label: "Bolt" },
    { value: "BU", label: "Butt" },
    { value: "BV", label: "Bottle, protected bulbous" },
    { value: "BW", label: "Box, for liquids" },
    { value: "BX", label: "Box" },
    { value: "BY", label: "Board, in bundle/bunch/truss" },
    { value: "BZ", label: "Bars, in bundle/bunch/truss" },
    { value: "CA", label: "Can, rectangular" },
    { value: "CB", label: "Beer crate" },
    { value: "CC", label: "Churn" },
    { value: "CD", label: "Can, with handle and spout" },
    { value: "CE", label: "Creel" },
    { value: "CF", label: "Coffer" },
    { value: "CG", label: "Cage" },
    { value: "CH", label: "Chest" },
    { value: "CI", label: "Canister" },
    { value: "CJ", label: "Coffin" },
    { value: "CK", label: "Cask" },
    { value: "CL", label: "Coil" },
    { value: "CM", label: "Card" },
    { value: "CN", label: "Cont,not otherwise specfied as transport equipment" },
    { value: "CO", label: "Carboy, non-protected" },
    { value: "CP", label: "Carboy, protected" },
    { value: "CQ", label: "Cartridge" },
    { value: "CR", label: "Crate" },
    { value: "CS", label: "Case" },
    { value: "CT", label: "Carton" },
    { value: "CU", label: "Cup" },
    { value: "CV", label: "Cover" },
    { value: "CW", label: "Cage, roll" },
    { value: "CX", label: "Can, cylindical" },
    { value: "CY", label: "Cylinder" },
    { value: "CZ", label: "Canvas" },
    { value: "DA", label: "Crate, multiple layer, plastic" },
    { value: "DB", label: "Crate, multiple layer, wooden" },
    { value: "DC", label: "Crate, multiple layer, cardboard" },
    { value: "DG", label: "Cage, Commonwealth Handling Equipment Pool (CHEP)" },
    { value: "DH", label: "Box,Commnwealth Hndling Equipmnt Pool/CHEP,Eurobox" },
    { value: "DI", label: "Drum, iron" },
    { value: "DJ", label: "Demijohn, non-protected" },
    { value: "DK", label: "Crate, bulk, cardboard" },
    { value: "DL", label: "Crate, bulk, plastic" },
    { value: "DM", label: "Crate, bulk, wooden" },
    { value: "DN", label: "Dispenser" },
    { value: "DP", label: "Demijohn, protected" },
    { value: "DR", label: "Drum" },
    { value: "DS", label: "Tray, one layer no cover, plastic" },
    { value: "DT", label: "Tray, one layer no cover, wooden" },
    { value: "DU", label: "Tray, one layer no cover, polystyrene" },
    { value: "DV", label: "Tray, one layer no cover, cardboard" },
    { value: "DW", label: "Tray, two layers no cover, plastic tray" },
    { value: "DX", label: "Tray, two layers no cover, wooden" },
    { value: "DY", label: "Tray, two layers no cover, cardboard" },
    { value: "EC", label: "Bag, plastic" },
    { value: "ED", label: "Case, with pallet base" },
    { value: "EE", label: "Case, with pallet base, wooden" },
    { value: "EF", label: "Case, with pallet base, cardboard" },
    { value: "EG", label: "Case, with pallet base, plastic" },
    { value: "EH", label: "Case, with pallet base, metal" },
    { value: "EI", label: "Case, isothermic" },
    { value: "EN", label: "Envelope" },
    { value: "FB", label: "Flexibag" },
    { value: "FC", label: "Fruit crate" },
    { value: "FD", label: "Framed crate" },
    { value: "FE", label: "Flexitank" },
    { value: "FI", label: "Firkin" },
    { value: "FL", label: "Flask" },
    { value: "FO", label: "Footlocker" },
    { value: "FP", label: "Filmpack" },
    { value: "FR", label: "Frame" },
    { value: "FT", label: "Foodtainer" },
    { value: "FW", label: "Cart, flatbed" },
    { value: "FX", label: "Bag, flexible container" },
    { value: "GB", label: "Gas bottle" },
    { value: "GI", label: "Girder" },
    { value: "GL", label: "Container, gallon" },
    { value: "GR", label: "Receptacle, glass" },
    { value: "GU", label: "Tray, containing horizontally stacked flat items" },
    { value: "GY", label: "Bag, gunny" },
    { value: "GZ", label: "Girders, in bundle/bunch/truss" },
    { value: "HA", label: "Basket, with handle, plastic" },
    { value: "HB", label: "Basket, with handle, wooden" },
    { value: "HC", label: "Basket, with handle, cardboard" },
    { value: "HG", label: "Hogshead" },
    { value: "HN", label: "Hanger" },
    { value: "HR", label: "Hamper" },
    { value: "HZ", label: "bukan kaleng kaleng" },
    { value: "IA", label: "Package, display, wooden" },
    { value: "IB", label: "Package, display, cardboard" },
    { value: "IC", label: "Package, display, plastic" },
    { value: "ID", label: "Package, display, metal" },
    { value: "IE", label: "Package, show" },
    { value: "IF", label: "Package, flow" },
    { value: "IG", label: "Package, paper wrapped" },
    { value: "IH", label: "Drum, plastic" },
    { value: "IK", label: "Package, cardboard, with bottle grip-holes" },
    { value: "IL", label: "Tray, rigid, lidded stackable (CEN TS 14482:2002)" },
    { value: "IN", label: "Ingot" },
    { value: "IZ", label: "ingots, in bundle/bunch/truss" },
    { value: "JB", label: "Bag, jumbo" },
    { value: "JC", label: "Jerrican, rectangular" },
    { value: "JG", label: "Jug" },
    { value: "JR", label: "Jar" },
    { value: "JT", label: "Jutebag" },
    { value: "JY", label: "Jerrican, cylindrical" },
    { value: "KG", label: "Keg" },
    { value: "KI", label: "Kit" },
    { value: "KR", label: "Karung" },
    { value: "LE", label: "Luggage" },
    { value: "LG", label: "Log" },
    { value: "LT", label: "Lot" },
    { value: "LU", label: "Lug" },
    { value: "LV", label: "Liftvan" },
    { value: "LZ", label: "Logs, in bundle/bunch/truss" },
    { value: "MA", label: "Crate, metal" },
    { value: "MB", label: "Multiply bag" },
    { value: "MC", label: "Milk crate" },
    { value: "ME", label: "Container, metal" },
    { value: "MR", label: "Receptacle, metal" },
    { value: "MS", label: "Multiwall sack" },
    { value: "MT", label: "Mat" },
    { value: "MW", label: "Receptacle, plastic wrapped" },
    { value: "MX", label: "Match box" },
    { value: "NA", label: "Not available" },
    { value: "NE", label: "Unpacked or unpackaged" },
    { value: "NF", label: "Unpacked or unpackaged, single unit" },
    { value: "NG", label: "Unpacked or unpackaged, multiple units" },
    { value: "NS", label: "Nest" },
    { value: "NT", label: "Net" },
    { value: "NU", label: "Net, tube, plastic" },
    { value: "NV", label: "Net, tube, textile" },
    { value: "OA", label: "Pallet, CHEP 40 cm x 60 cm" },
    { value: "OB", label: "Pallet, CHEP 80 cm x 120 cm" },
    { value: "OC", label: "Pallet, CHEP 100 cm x 120 cm" },
    { value: "OD", label: "Pallet, AS 4068-1993" },
    { value: "OE", label: "Pallet, ISO T11" },
    { value: "OF", label: "Platform, unspecified weight or dimension" },
    { value: "OK", label: "Block" },
    { value: "OT", label: "Octabin" },
    { value: "OU", label: "Container, outer" },
    { value: "P2", label: "Pan" },
    { value: "PA", label: "Packet" },
    { value: "PB", label: "Pallet, box Combined open-ended box and pallet" },
    { value: "PC", label: "Parcel" },
    { value: "PD", label: "Pallet, modular, collars 80cms * 100cms" },
    { value: "PE", label: "Pallet, modular, collars 80cms * 120cms" },
    { value: "PF", label: "Pen" },
    { value: "PG", label: "Plate" },
    { value: "PH", label: "Pitcher" },
    { value: "PI", label: "Pipe" },
    { value: "PJ", label: "Punnet" },
    { value: "PK", label: "Package" },
    { value: "PL", label: "Pail" },
    { value: "PN", label: "Plank" },
    { value: "PO", label: "Pouch" },
    { value: "PP", label: "Piece" },
    { value: "PR", label: "Receptacle, plastic" },
    { value: "PT", label: "Pot" },
    { value: "PU", label: "Tray" },
    { value: "PV", label: "Pipes, in bundle/bunch/truss" },
    { value: "PX", label: "Pallet" },
    { value: "PY", label: "Plates, in bundle/bunch/truss" },
    { value: "PZ", label: "Pipes, in bundle/bunch/truss" },
    { value: "QA", label: "Drum, steel, non-removable head" },
    { value: "QB", label: "Drum, steel, removable head" },
    { value: "QC", label: "Drum, aluminium, non-removable head" },
    { value: "QD", label: "Drum, aluminium, removable head" },
    { value: "QF", label: "Drum, plastic, non-removable head" },
    { value: "QG", label: "Drum, plastic, removable head" },
    { value: "QH", label: "Barrel, wooden, bung type" },
    { value: "QJ", label: "Barrel, wooden, removable head" },
    { value: "QK", label: "Jerrican, steel, non-removable head" },
    { value: "QL", label: "Jerrican, steel, removable head" },
    { value: "QM", label: "Jerrican, plastic, non-removable head" },
    { value: "QN", label: "Jerrican, plastic, removable head" },
    { value: "QP", label: "Box, wooden, natural wood, ordinary" },
    { value: "QQ", label: "Box, wooden, natural wood, with sift proof walls" },
    { value: "QR", label: "Box, plastic, expanded" },
    { value: "QS", label: "Box, plastic, solid" },
    { value: "RD", label: "Rod" },
    { value: "RG", label: "Ring" },
    { value: "RJ", label: "Rack, clothing hanger" },
    { value: "RK", label: "Rack" },
    { value: "RL", label: "Reel" },
    { value: "RO", label: "Roll" },
    { value: "RT", label: "Rednet" },
    { value: "RZ", label: "Rods, in bundle/ bunch/truss" },
    { value: "SA", label: "Sack" },
    { value: "SB", label: "Slab" },
    { value: "SC", label: "Shallow crate" },
    { value: "SD", label: "Spindle" },
    { value: "SE", label: "Sea-chest" },
    { value: "SH", label: "Sachet" },
    { value: "SI", label: "Skid" },
    { value: "SK", label: "Skeleton case" },
    { value: "SL", label: "Slipsheet" },
    { value: "SM", label: "Sheetmetal" },
    { value: "SO", label: "Spool" },
    { value: "SP", label: "Sheet, plastic wrapping" },
    { value: "SS", label: "Case, steel" },
    { value: "ST", label: "Sheet" },
    { value: "SU", label: "Suitcase" },
    { value: "SV", label: "Envelope, steel" },
    { value: "SW", label: "Shrinkwrapped" },
    { value: "SX", label: "Set" },
    { value: "SY", label: "Sleeve" },
    { value: "SZ", label: "Sheets, in bundle/bunch/truss" },
    { value: "T1", label: "Tablet" },
    { value: "TB", label: "Tub" },
    { value: "TC", label: "Tea-chest" },
    { value: "TD", label: "Collapsible tube" },
    { value: "TE", label: "Tyre" },
    { value: "TG", label: "Tank container, generic" },
    { value: "TI", label: "Tierce" },
    { value: "TK", label: "Tank, rectangular" },
    { value: "TL", label: "Tub, with lid" },
    { value: "TN", label: "Tin" },
    { value: "TO", label: "Tun" },
    { value: "TP", label: "Tray" },
    { value: "TR", label: "Trunk" },
    { value: "TS", label: "Truss" },
    { value: "TT", label: "Bag, tote" },
    { value: "TU", label: "Tube" },
    { value: "TV", label: "Tube, with nozzle" },
    { value: "TW", label: "Pallet, triwall" },
    { value: "TY", label: "Tank, cylindrical" },
    { value: "TZ", label: "Tubes, in bundle/bunch/truss" },
    { value: "UC", label: "Uncaged" },
    { value: "UN", label: "Unpackage" },
    { value: "VA", label: "Vat" },
    { value: "VG", label: "Bulk, gas ( at 1031 mbar and 15C )" },
    { value: "VI", label: "Vial" },
    { value: "VK", label: "Vanpack" },
    { value: "VL", label: "Bulk, liquid" },
    { value: "VN", label: "Vehicle" },
    { value: "VO", label: "Bulk, solid, large particles (\"nodules\")" },
    { value: "VP", label: "Vacuumpacked" },
    { value: "VQ", label: "Bulk,liquefied gas (at abnorml temprture/pressure)" },
    { value: "VR", label: "Bulk, solid, granular particles (\"grains\")" },
    { value: "VS", label: "Bulk, scrap metal" },
    { value: "VY", label: "Bulk, solid, fine particles (\"powders\")" },
    { value: "WA", label: "Intermediate bulk container" },
    { value: "WB", label: "Wickerbottle" },
    { value: "WC", label: "Intermediate bulk container, steel" },
    { value: "WD", label: "Intermediate bulk container, aluminium" },
    { value: "WF", label: "Intermediate bulk container, metal" },
    { value: "WG", label: "Intermediate bulk cont,steel,pressurised >10 kpa" },
    { value: "WH", label: "Intermedt bulk cont,aluminium,pressurised >10 kpa" },
    { value: "WJ", label: "Intermediate bulk container,metal, pressure 10 kpa" },
    { value: "WK", label: "Intermediate bulk container, steel, liquid" },
    { value: "WL", label: "Intermediate bulk container, aluminium, liquid" },
    { value: "WM", label: "Intermediate bulk container, metal, liquid" },
    { value: "WN", label: "Intermd bulk cont,woven plastic,without coat/liner" },
    { value: "WP", label: "Intermediate bulk container, woven plastic, coated" },
    { value: "WQ", label: "Intermediate bulk cont,woven plastic,with liner" },
    { value: "WR", label: "Intermedt bulk cont,woven plastic,coated and liner" },
    { value: "WS", label: "Intermediate bulk container, plastic film" },
    { value: "WT", label: "Intermediate bulk cont,textile with out coat/liner" },
    { value: "WU", label: "Intermdte bulk cont,natural wood,with inner liner" },
    { value: "WV", label: "Intermediate bulk container, textile, coated" },
    { value: "WW", label: "Intermediate bulk container, textile, with liner" },
    { value: "WX", label: "Intermediate bulk cont,textile,coated and liner" },
    { value: "WY", label: "Intermediate bulk cont,plywood,with inner liner" },
    { value: "WZ", label: "Intermd bulk cont,reconstttd wood,with inner liner" },
    { value: "XA", label: "Bag, woven plastic, without inner coat/liner" },
    { value: "XB", label: "Bag, woven plastic, sift proof" },
    { value: "XC", label: "Bag, woven plastic, water resistant" },
    { value: "XD", label: "Bag, plastics film" },
    { value: "XF", label: "Bag, textile, without inner coat/liner" },
    { value: "XG", label: "Bag, textile, sift proof" },
    { value: "XH", label: "Bag, textile, water resistant" },
    { value: "XJ", label: "Bag, paper, multi-wall" },
    { value: "XK", label: "Bag, paper, multi-wall, water resistant" },
    { value: "XN", label: "test" },
    { value: "YA", label: "Compsite packging,plastic receptacle in steel drum" },
    { value: "YB", label: "Compste packgng,plastc recptcle in steel crate box" },
    { value: "YC", label: "Compste packgng,plastic recptcle in aluminium drum" },
    { value: "YD", label: "Compste packgng,plastic recptcle in alumnium crate" },
    { value: "YF", label: "Compsite packging,plastic receptacle in wooden box" },
    { value: "YG", label: "Compste packgng,plastic receptacle in plywood drum" },
    { value: "YH", label: "Compste packging,plastic receptacle in plywood box" },
    { value: "YJ", label: "Compsite packging,plastic receptacle in fibre drum" },
    { value: "YK", label: "Compste packgng,plastic recptcle in fibreboard box" },
    { value: "YL", label: "Compste packgng,plstc recptcle in plastic drum" },
    { value: "YM", label: "Compsite packgng,plstc recptcle in solid plstc box" },
    { value: "YN", label: "Composite packaging,glass receptacle in steel drum" },
    { value: "YP", label: "Compste packgng,glass recptacle in steel crate box" },
    { value: "YQ", label: "Compste packgng,glass recptacle in aluminium drum" },
    { value: "YR", label: "Compste packgng,glass recptacle in aluminium crate" },
    { value: "YS", label: "Composite packaging,glass receptacle in wooden box" },
    { value: "YT", label: "Compsite packging,glass receptacle in plywood drum" },
    { value: "YV", label: "Compste packgng,glass recptcle in wickrwork hamper" },
    { value: "YW", label: "Composite packaging,glass receptacle in fibre drum" },
    { value: "YX", label: "Compste packgng,glass recptacle in fibreboard box" },
    { value: "YY", label: "Compste pckgng,glss recptcl in expndbl plastc pack" },
    { value: "YZ", label: "Compsite packgng,glass recptcle in solid plstc pck" },
    { value: "ZA", label: "Intermediate bulk container, paper, multi-wall" },
    { value: "ZB", label: "Bag, large" },
    { value: "ZC", label: "Intermd bulk cont,paper,multi-wall,water resistant" },
    { value: "ZD", label: "Intermd bulk cont,rgd plstc,w/strctrl equipm,solid" },
    { value: "ZF", label: "Intermd bulk cont,rgid plstc,freestandng,solds" },
    { value: "ZG", label: "Intermdbulk cnt,rgd plstc,w/strctrl equipm,pressrd" },
    { value: "ZH", label: "Intermd bulk cont,rgd plstc,freestnd,pressurised" },
    { value: "ZJ", label: "Intermd bulk cont,rgd plstc,w/strctrl equipm,lquid" },
    { value: "ZK", label: "Intermd bulk cont,rgid plstc,freestanding,liquids" },
    { value: "ZL", label: "Intermd bulk cont,composite,rigid plastic,solids" },
    { value: "ZM", label: "Intermd bulk cont,compste,flexbl plastic, solids" },
    { value: "ZN", label: "Intermd bulk cont,compsit,rgid plstc,pressurised" },
    { value: "ZP", label: "Intermd bulk cont,compsite,flexbl plstc,pressurised" },
    { value: "ZQ", label: "Intermd bulk cont,composite,rigid plastic,liquids" },
    { value: "ZR", label: "Intermd bulk cont,compsite,flexible plastc,liquids" },
    { value: "ZS", label: "Intermediate bulk container, composite" },
    { value: "ZT", label: "Intermediate bulk container, fibreboard" },
    { value: "ZU", label: "Intermediate bulk container, flexible" },
    { value: "ZV", label: "Intermediate bulk container,metal,other than steel" },
    { value: "ZW", label: "Intermediate bulk container, natural wood" },
    { value: "ZX", label: "Intermediate bulk container, plywood" },
    { value: "ZY", label: "Intermediate bulk container, reconstituted wood" },
    { value: "ZZ", label: "Mutually defined" },
];